### ISSUE TITLE
Swift Package Manager supporting?

### ISSUE THREAD

**Issue by AlexIzh** [Adnuntius/ios_sdk#6]
Do you plan to add supporting of SPM? It would be very useful.

**Comment by jason-adnuntius** [comment]
After looking at this, seems like maybe it does not support Objective-C?  Which is a problem as we have customers who use it.

If you really want to see the SDK use SPM instead of Carthage, a MR applied to the ios_sdk_examples project showing how all the example projects can be converted to using SPM, would go a long way to convincing me to replace Carthage with SPM.

For now at least, I do not have the time to invest in migrating to SPM from Carthage

Regards
Jason

**Comment by AlexIzh** [comment]
You do not need to choose between SPM and Carthage, you are providing a library which could(and should) support so much different package managers as possible, you can support both and SPM and Carthage. The client should decide what to use. 
SPM doesn't conflict with Carthage

**Comment by jason-adnuntius** [comment]
Thanks for your contribution, and thanks for taking the time to explain SPM vs Carthage.

**Comment by jason-adnuntius** [comment]
release 1.5.1 with your SPM file plus a few other fixes was just released, thanks again.
